name: Deploy to Server TENCENT LIGHTHOUSE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TCLH_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.TCLH_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Sync www directory to Server B
        run: |
          rsync -avz --delete www/ ${{ secrets.TCLH_SERVER_USER }}@${{ secrets.TCLH_SERVER_IP }}:${{ secrets.TCLH_SERVER_PATH }}
